source :rubygems

gem "capybara"
gem "cucumber", :git => "https://github.com/mcrmfc/cucumber-ruby"
gem "rspec", :require => "spec"
gem "parallel_tests"
gem "poltergeist"
gem "selenium-webdriver"
gem "capybara-accessible"
gem "cuke_sniffer"
gem "parallel"
gem "json"
gem "rake"
gem "yard-cucumber"
gem "redcarpet"
gem "rubocop"
